String getEmojiForInterest(String interest) {
  final Map<String, String> emojiMap = {
    'art': '🎨',
    'foodie': '🌭',
    'makeup': '💄',
    'astrology': '🪐',
    'music': '🎵',
    'travel': '✈️',
    'sports': '⚽',
    'reading': '📚',
    'gaming': '🎮',
    'photography': '📷',
    'cooking': '👨‍🍳',
    'dance': '💃',
    'dancing': '💃',
    'fitness': '🏋️‍♂️',
    'movies': '🎬',
    'nature': '🌿',
    'technology': '💻',
    'yoga': '🧘‍♂️',
    'fashion': '👗',
    'animals': '🐾',
    'environment': '🌍',
    'science': '🔬',
    'history': '🏛️',
    'languages': '🈴',
    'architecture': '🏰',
    'astronomy': '🔭',
    'gardening': '🌻',
    'hiking': '🥾',
    'skateboarding': '🛹',
    'surfing': '🏄‍♀️',
    'politics': '🏛️',
    'volunteering': '🤝',
    'meditation': '🧘',
    'self-care': '🛀',
    'camping': '🏕️',
    'shopping': '🛍️',
    'investing': '📈',
    'baking': '🍰',
    'pets': '🐶',
    'theater': '🎭',
    'comedy': '😂',
    'tattoos': '💉',
    'motorcycles': '🏍️',
    'cars': '🚗',
    'sailing': '⛵',
    'kitesurfing': '🪁',
    'martial arts': '🥋',
    'crafting': '✂️',
    'hunting': '🏹',
    'fishing': '🎣',
    'blogging': '💻',
    'entrepreneurship': '💼',
    'video editing': '🎥',
    'podcasting': '🎙️',
    'philosophy': '🧠',
    'diy projects': '🛠️',
    'board games': '🎲',
    'puzzles': '🧩',
    'collecting': '📦',
    'writing': '✍️',
    'traveling': '🧳',
    'swimming': '🏊‍♂️',
    'tech': '🖥️',
    'socializing': '👥',
    'gym': '🏋️',
    'self development': '📖',
    'self made': '💰',
    'songwriting': '📝',
    'freelancing': '💼',
    'expositions': '🏛️',
    'singing': '🎤',
    'learning languages': '🗣️',
    'painting': '🖌️',
    'stock exchange': '📊',
    'brunch': '🥐',
    'coffee': '☕',
    'tea': '🍵',
    'ice cream': '🍦',
    'enjoying the sun': '☀️',
    'tanning': '🌞',
    'travel the world': '🌍',
    'sushi': '🍣',
    'riding motorcycle': '🏍️',
    'working out': '💪',
    'lounges': '🛋️',
    'clubs': '🎶',
    'restaurants': '🍽️',
    'thrifting': '🛒',
    'comedy shows': '😂',
    'playing instruments': '🎸',
    'bars': '🍻',
    'parties': '🎉',
    'nightlife': '🌃',
    'film festival': '🎥',
    'pubs': '🍺',
    'concerts': '🎶',
    'town festivities': '🏘️',
    'gospel music': '🎶',
    'rock music': '🎸',
    'poetry': '📜',
    'pizza': '🍕',
    'burgers': '🍔',
    'rowing': '🚣',
    'skydiving': '🪂',
    'wine & dine': '🍷',
    'clean freak': '🧼',
    'jazz': '🎷',
    'hip hop': '🎤',
    'outdoors': '🏞️',
    'picnicking': '🧺',
    'instagram': '📱',
    'tik tok': '🎥',
    'snowboarding': '🏂',
    'walking my dog': '🐕',
    'walking': '🚶',
    'christmas holidays': '🎄',
    'ramadan': '🌙',
    'religious': '🙏',
    'going to church': '⛪',
    'making lists': '📝',
    'making puzzles': '🧩',
    'hard alcohol': '🥃',
    'visiting farms': '🚜',
    'farmer': '👨‍🌾',
    'opera': '🎭',
    'heavy metal': '🤘',
    'working on cars': '🔧',
    'renovations': '🏠',
    'comicon': '🎭',
    'paragliding': '🪂',
    'diving': '🤿',
    'deep diving': '🌊',
    'jet skiing': '🚤',
    'snorkeling': '🤿',
    'mexican food': '🌮',
    'chinese food': '🥡',
    'arabic food': '🍛',
    'learning new cultures': '🌎',
    'trying new ways': '🔄',
    'easy going': '😊',
    'documentaries': '📺',
  };

  String lowercaseInterest = interest.toLowerCase();
  return emojiMap[lowercaseInterest] ?? '🌟';
}
